server {
    listen 80;
    listen [::]:80;
    server_name lipicturecloud.com www.lipicturecloud.com;

    location ^~ /.well-known/acme-challenge/ {
        root /usr/share/nginx/html;
        default_type text/plain;
        try_files $uri =404;
    }

    location / {
        return 503;
    }
}
