spring:
  application:
    name: li-picture-cloud
  datasource:
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:li_picture_cloud_data}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  autoconfigure:
    exclude:
      - org.springframework.ai.model.ollama.autoconfigure.OllamaEmbeddingAutoConfiguration
      - org.springframework.ai.model.ollama.autoconfigure.OllamaChatAutoConfiguration
      - org.springframework.ai.vectorstore.pgvector.autoconfigure.PgVectorStoreAutoConfiguration
      - org.springframework.ai.mcp.client.common.autoconfigure.McpToolCallbackAutoConfiguration
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 50MB
  ai:
    dashscope:
      chat:
        options:
          model: qwen-max
    mcp:
      client:
        sse:
          connections:
            mxai-mcp-server:
              url: https://mcp.mxai.cn
              sse-endpoint: /sse
  # Redis 配置
  data:
    redis:
      database: 15
      host: 127.0.0.1
      port: 6379
      timeout: 5000
      password: ${REDIS_PASSWORD}
  session:
    store-type: redis
    timeout: 2592000          # 30天（秒）
    cookie:
      max-age: 2592000        # 同样30天，与timeout保持同步
  config:
    activate:
      on-profile: local



server:
  port: 8124
  servlet:
    context-path: /api

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
  packages-to-scan:
    - com.li.lipicturecloud.controller
  paths-to-exclude:
    - /actuator/**

