import { test, expect } from '@playwright/test'

const member = { id: '42', userName: 'R08', userRole: 'user' }
const specimen = { id: '7001', lifeStage: 'LIGHT', lifeExperience: '42', level: 1, levelStartExperience: '0', nextLevelExperience: '100', revision: '9', traits: {}, skills: [] }
const space = { id: '51', userId: '42', spaceType: 0, spaceName: '我的私有空间', createTime: '2026-09-27T00:00:00Z' }
const photo = { id: '11', spaceId: '51', userId: '42', name: '候选图片', url: '/favicon.svg', picWidth: 300, picHeight: 200, picSize: 200, picFormat: 'svg' }
const ok = (route, data) => route.fulfill({ json: { code: 0, data } })
function gate() { let release; const promise = new Promise(resolve => { release = resolve }); return { promise, release } }
async function fixture(page) {
  const state = { photo: { ...photo }, space: { ...space }, calls: [], errors: [] }
  page.on('pageerror', error => state.errors.push(error.message))
  await page.route(url => url.pathname.startsWith('/api/'), route => {
    const url = new URL(route.request().url())
    state.calls.push({ path: url.pathname, method: route.request().method(), body: route.request().postDataJSON() })
    if (url.pathname === '/api/user/current') return ok(route, member)
    if (url.pathname === '/api/picture/get/vo') return ok(route, { ...state.photo, id: url.searchParams.get('id') })
    if (url.pathname === '/api/space/get/vo') return ok(route, state.space)
    if (url.pathname === '/api/spaceUser/permissions') return ok(route, ['picture:view'])
    if (url.pathname.includes('tag_category')) return ok(route, { tagList: [], categoryList: [] })
    if (url.pathname.includes('/picture/list/page')) return ok(route, { records: [state.photo, { ...photo, id: '12', name: '另一张图片' }], total: 2 })
    if (url.pathname === '/api/space/list/page/vo') return ok(route, { records: [space], total: 1 })
    if (url.pathname === '/api/companion/me') return ok(route, { companion: specimen, recentGrowth: [], nutrition: {}, mood: null, relationship: null, chatPolicy: 'DEMO' })
    if (url.pathname === '/api/companion/proposals/active') return ok(route, null)
    if (url.pathname === '/api/companion/contract') return ok(route, { active: false, quietStart: '23:00', quietEnd: '08:00', maxFrequencyHours: 1 })
    return ok(route, { records: [], total: 0 })
  })
  return state
}
const panel = page => page.getByRole('dialog', { name: '和绫页互动' })
const shell = page => page.locator('.sidebar').getByRole('button', { name: '和绫页互动' })
function noFeed(state) { expect(state.calls.filter(call => call.path === '/api/companion/feed')).toEqual([]) }
async function ticketDrop(page, source, target = '.sidebar .presence') {
  const dataTransfer = await page.evaluateHandle(() => new globalThis.DataTransfer())
  await source.dispatchEvent('dragstart', { dataTransfer })
  await page.locator(target).dispatchEvent('dragover', { dataTransfer })
  await page.locator(target).dispatchEvent('drop', { dataTransfer })
  await source.dispatchEvent('dragend', { dataTransfer })
  await dataTransfer.dispose()
}

test('Shell keyboard interaction traps focus, restores it and does not manufacture global state', async ({ page }, testInfo) => {
  const state = await fixture(page)
  await page.goto('/gallery')
  await shell(page).focus()
  await expect(panel(page)).not.toBeVisible()
  await page.keyboard.press('Enter')
  await expect(panel(page)).toBeVisible()
  await expect(page.locator('dialog[open]')).toHaveCount(1)
  await expect(panel(page).getByRole('button', { name: '关闭菜单' })).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await expect(panel(page).getByRole('link', { name: '前往我的空间选图' })).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(panel(page).getByRole('button', { name: '关闭菜单' })).toBeFocused()
  await page.screenshot({ path: testInfo.outputPath('interaction-desktop.png') })
  await page.keyboard.press('Escape')
  await expect(shell(page)).toBeFocused()
  await expect(page.locator('body')).not.toHaveCSS('overflow', 'hidden')
  expect(state.calls.some(call => call.path.startsWith('/api/companion/'))).toBe(false)
  await shell(page).click()
  await panel(page).getByRole('button', { name: /聊一聊/ }).click()
  await expect(page).toHaveURL(/\/companion$/)
  await expect(page.getByLabel('对伙伴说的话')).toBeFocused()
  await page.locator('.portrait-interaction').click()
  await panel(page).getByRole('button', { name: /选择图片/ }).click()
  await expect(page.locator('#feeding-title')).toBeFocused()
  noFeed(state)
  expect(state.errors).toEqual([])
})

test('navigation drawer hands off to one interaction dialog and legacy overlays isolate triggers', async ({ page }) => {
  const state = await fixture(page)
  await page.setViewportSize({ width: 820, height: 900 })
  await page.goto('/picture/11')
  await page.getByRole('button', { name: '打开导航菜单' }).click()
  await page.getByRole('dialog', { name: '导航', exact: true }).getByRole('button', { name: '和绫页互动' }).click()
  await expect(panel(page)).toBeVisible()
  await expect(page.locator('dialog[open]')).toHaveCount(1)
  await page.keyboard.press('Escape')
  await expect(page.locator('body')).not.toHaveCSS('overflow', 'hidden')
  await page.getByRole('button', { name: '分享', exact: true }).click()
  await expect(page.locator('.sidebar')).toHaveAttribute('inert', '')
  await expect(panel(page)).not.toBeVisible()
  noFeed(state)
  expect(state.errors).toEqual([])
})

test('chat handoff does not wait for an unrelated slow private-picture source', async ({ page }) => {
  const state = await fixture(page)
  const held = gate()
  await page.route('**/api/space/list/page/vo', async route => { await held.promise; await ok(route, { records: [space] }) })
  await page.goto('/gallery')
  await shell(page).click()
  await panel(page).getByRole('button', { name: /聊一聊/ }).click()
  try {
    await expect(page.getByLabel('对伙伴说的话')).toBeFocused()
    noFeed(state)
  } finally { held.release() }
})

test('native Gallery drag opens a verified candidate and hands off only a selection', async ({ page }) => {
  const state = await fixture(page)
  await page.goto('/gallery')
  await page.locator('.gallery-card').first().dragTo(page.locator('.sidebar .presence'))
  await expect(panel(page).getByText('候选图片', { exact: true })).toBeVisible()
  await panel(page).getByRole('button', { name: '在伙伴空间选择这张' }).click()
  await expect(page.getByRole('button', { name: /候选图片/ })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByText('已选择这张图片；点击「喂给伙伴」才会开始喂养。')).toBeVisible()
  await expect(page.getByRole('button', { name: '喂给伙伴', exact: true })).toBeEnabled()
  expect(state.calls.filter(call => call.path === '/api/picture/get/vo')).toHaveLength(2)
  noFeed(state)
  expect(state.errors).toEqual([])
})

test('external and forged drops are ignored; public, team and other-owner candidates are explained', async ({ page }) => {
  const state = await fixture(page)
  await page.goto('/gallery')
  for (const type of ['text/uri-list', 'application/x-lipicturecloud-companion-picture']) {
    const dataTransfer = await page.evaluateHandle(type => { const dt = new globalThis.DataTransfer(); dt.setData(type, '11'); return dt }, type)
    await page.locator('.sidebar .presence').dispatchEvent('drop', { dataTransfer })
    await dataTransfer.dispose()
    await expect(panel(page)).not.toBeVisible()
  }
  expect(state.calls.some(call => call.path === '/api/picture/get/vo')).toBe(false)
  for (const kind of ['public', 'team', 'other']) {
    state.photo.spaceId = kind === 'public' ? null : '51'
    state.space = { ...space, spaceType: kind === 'team' ? 1 : 0, userId: kind === 'other' ? '43' : '42' }
    await ticketDrop(page, page.locator('.gallery-card').first())
    await expect(panel(page).getByRole('alert')).toContainText('仅支持你自己的私有空间')
    await expect(panel(page).getByRole('button', { name: '在伙伴空间选择这张' })).toHaveCount(0)
    await page.keyboard.press('Escape')
  }
  noFeed(state)
  expect(state.errors).toEqual([])
})

test('closing an inspection discards its late reply; arrival rechecks revoked access', async ({ page }) => {
  const state = await fixture(page)
  const held = gate()
  await page.goto('/picture/11')
  await page.route('**/api/picture/get/vo?id=11', async route => { await held.promise; await ok(route, photo) })
  await page.getByRole('button', { name: '选给绫页' }).click()
  await expect(panel(page).getByRole('status')).toBeVisible()
  await page.keyboard.press('Escape')
  held.release()
  await shell(page).click()
  await expect(panel(page).locator('.interaction-picture')).toHaveCount(0)
  await page.keyboard.press('Escape')
  await page.unroute('**/api/picture/get/vo?id=11')
  await page.getByRole('button', { name: '选给绫页' }).click()
  await expect(panel(page).getByRole('button', { name: '在伙伴空间选择这张' })).toBeVisible()
  await page.route('**/api/picture/get/vo?id=11', route => route.fulfill({ status: 403, json: { code: 40101, message: 'revoked' } }))
  await panel(page).getByRole('button', { name: '在伙伴空间选择这张' }).click()
  await expect(page.getByText('图片已不可用或不在你的私有空间，未更改当前选择。')).toBeVisible()
  await expect(page.getByRole('button', { name: '喂给伙伴', exact: true })).toBeDisabled()
  noFeed(state)
  expect(state.errors).toEqual([])
})

test('R07 arbitrates hover/focus, modal interruption, pause and reduced motion', async ({ page }) => {
  const state = await fixture(page)
  await page.clock.install()
  await page.clock.pauseAt(new Date())
  await page.goto('/companion')
  const player = page.locator('.sprite-player')
  const body = page.locator('.body-ground')
  await expect(player).toHaveAttribute('data-animation-state', 'idle')
  await body.hover()
  await expect(player).toHaveAttribute('data-animation-state', 'greeting')
  await page.clock.runFor(160)
  await expect(player).toHaveAttribute('data-frame', '1')
  await page.clock.runFor(300)
  await expect(player).toHaveAttribute('data-animation-state', 'idle')
  await body.click()
  await expect(player).toHaveAttribute('data-animation-state', 'static')
  await page.keyboard.press('Escape')
  await expect(body).toBeFocused()
  await expect(player).toHaveAttribute('data-playback', 'playing')
  await page.getByRole('button', { name: '暂停动作' }).click()
  await body.focus()
  await expect(player).toHaveAttribute('data-animation-state', 'static')
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await body.click()
  await expect(panel(page)).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(player).toHaveAttribute('data-frame', '0')
  noFeed(state)
  expect(state.errors).toEqual([])
})

test('manual selection cancels a pending handoff and its waiting message', async ({ page }) => {
  const state = await fixture(page)
  const held = gate()
  await page.goto('/companion')
  await ticketDrop(page, page.getByRole('button', { name: /候选图片/ }).locator('img'), '.body-ground')
  await expect(panel(page).getByRole('button', { name: '在伙伴空间选择这张' })).toBeVisible()
  await page.route('**/api/picture/get/vo?id=11', async route => { await held.promise; await ok(route, photo) })
  await panel(page).getByRole('button', { name: '在伙伴空间选择这张' }).click()
  await expect(page.getByText('正在重新确认图片…')).toBeVisible()
  try {
    await page.getByRole('button', { name: /另一张图片/ }).click()
    await expect(page.getByText('正在重新确认图片…')).not.toBeVisible()
  } finally { held.release() }
  await expect(page.getByRole('button', { name: /另一张图片/ })).toHaveAttribute('aria-pressed', 'true')
  noFeed(state)
  expect(state.errors).toEqual([])
})

test('uncertain feed retains its key and selection when another picture is handed off', async ({ page }) => {
  const state = await fixture(page)
  const keys = []
  await page.route('**/api/companion/feed', route => { keys.push(route.request().postDataJSON()); return route.abort('failed') })
  await page.goto('/companion')
  await page.getByRole('button', { name: /候选图片/ }).click()
  await page.getByRole('button', { name: '喂给伙伴', exact: true }).click()
  await expect(page.getByRole('button', { name: '重试这次喂养' })).toBeVisible()
  await ticketDrop(page, page.getByRole('button', { name: /另一张图片/ }).locator('img'), '.body-ground')
  await expect(panel(page).getByRole('button', { name: '在伙伴空间选择这张' })).toBeVisible()
  await panel(page).getByRole('button', { name: '在伙伴空间选择这张' }).click()
  await expect(page.getByText('请先完成或重试当前喂养，再选择新图片。当前选择已保留。')).toBeVisible()
  await expect(page.getByRole('button', { name: /候选图片/ })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: '重试这次喂养' }).click()
  await expect.poll(() => keys.length).toBe(2)
  expect(keys[1]).toEqual(keys[0])
  expect(state.errors).toEqual([])
})

test.describe('touch fallback', () => {
  test.use({ viewport: { width: 390, height: 844 }, hasTouch: true, isMobile: true })
  test('bottom trigger and detail action remain usable without drag or hover', async ({ page }, testInfo) => {
    const state = await fixture(page)
    await page.goto('/picture/11')
    await page.locator('.bottom-navigation .companion-tab').tap()
    await expect(panel(page)).toBeVisible()
    await page.screenshot({ path: testInfo.outputPath('interaction-mobile.png') })
    await panel(page).getByRole('button', { name: '关闭菜单' }).tap()
    await page.getByRole('button', { name: '选给绫页' }).tap()
    await expect(panel(page).getByRole('button', { name: '在伙伴空间选择这张' })).toBeVisible()
    await panel(page).getByRole('button', { name: '在伙伴空间选择这张' }).tap()
    await expect(page.getByRole('button', { name: /候选图片/ })).toHaveAttribute('aria-pressed', 'true')
    expect(await page.evaluate(() => globalThis.document.documentElement.scrollWidth <= globalThis.innerWidth)).toBe(true)
    noFeed(state)
    expect(state.errors).toEqual([])
  })
})
